name: assist_lens
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_tts: ^4.2.3
  image_picker: ^1.1.2
  http: ^1.4.0 # Downgraded to be compatible with flutter_mjpeg
  http_parser: ^4.1.2
  mime: ^2.0.0
  camera: ^0.11.1
  camera_android: ^0.10.10+3
  logger: ^2.5.0
  image: ^4.5.4
  speech_to_text: ^7.0.0
  shared_preferences: ^2.1.1
  google_ml_kit: ^0.20.0
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_commons: ^0.11.0
  google_mlkit_object_detection: ^0.15.0
  google_mlkit_image_labeling: ^0.14.1
  flutter_webrtc: ^0.14.0
  geolocator: ^14.0.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  url_launcher: ^6.3.1
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.4
  web_socket_channel: ^3.0.3
  provider: ^6.1.5
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  location: ^8.0.0
  flutter_map_location_marker: ^10.1.0
  sensors_plus: ^6.1.1
  vibration: ^3.1.3
  firebase_core: ^3.13.0
  tflite_flutter: ^0.11.0
  sqflite: ^2.4.1
  geocoding: ^3.0.0
  intl: ^0.20.2
  porcupine_flutter: ^3.0.4
  flutter_staggered_grid_view: ^0.7.0
  lottie: ^3.3.1
  google_maps_flutter: ^2.12.2
  flutter_svg: ^2.1.0
  animated_text_kit: ^4.2.3
  gal: ^2.3.1
  socket_io_client: ^3.1.2
  flutter_mjpeg: ^2.0.4
  just_audio: ^0.10.4
  audioplayers: ^6.5.0
  package_info_plus: ^4.2.0
  app_installer: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding/slide1.png
    - assets/images/onboarding/slide2.png
    - assets/images/onboarding/slide3.png
    - assets/ml/
    - assets/ml/mobile_face_net.tflite
    - assets/ml/coco_label.txt
    - assets/ml/ssd_mobilenet.tflite
    - assets/animations/
dependency_overrides:
  http: ^0.13.6 # Ensure http is compatible with flutter_mjpeg
